[2021-03-16 00:56:28,626] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: marketvol.get_apple_data 2021-03-16T00:56:17.933716+00:00 [queued]>
[2021-03-16 00:56:28,697] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: marketvol.get_apple_data 2021-03-16T00:56:17.933716+00:00 [queued]>
[2021-03-16 00:56:28,698] {{taskinstance.py:880}} INFO - 
--------------------------------------------------------------------------------
[2021-03-16 00:56:28,698] {{taskinstance.py:881}} INFO - Starting attempt 1 of 3
[2021-03-16 00:56:28,698] {{taskinstance.py:882}} INFO - 
--------------------------------------------------------------------------------
[2021-03-16 00:56:28,712] {{taskinstance.py:901}} INFO - Executing <Task(PythonOperator): get_apple_data> on 2021-03-16T00:56:17.933716+00:00
[2021-03-16 00:56:28,716] {{standard_task_runner.py:54}} INFO - Started process 14579 to run task
[2021-03-16 00:56:28,812] {{standard_task_runner.py:77}} INFO - Running: ['airflow', 'run', 'marketvol', 'get_apple_data', '2021-03-16T00:56:17.933716+00:00', '--job_id', '34', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/stock-market-dag.py', '--cfg_path', '/tmp/tmpp6xv3yh8']
[2021-03-16 00:56:28,813] {{standard_task_runner.py:78}} INFO - Job 34: Subtask get_apple_data
[2021-03-16 00:56:28,884] {{logging_mixin.py:112}} INFO - Running <TaskInstance: marketvol.get_apple_data 2021-03-16T00:56:17.933716+00:00 [running]> on host 6ef8928b229b
[2021-03-16 00:56:29,207] {{logging_mixin.py:112}} INFO - [*********************100%***********************]  1 of 1 completed
[2021-03-16 00:56:29,207] {{logging_mixin.py:112}} INFO - 
[2021-03-16 00:56:29,212] {{taskinstance.py:1150}} ERROR - [Errno 2] No such file or directory: '/usr/local/spark/resources/data/tmp/2021-03-15/aapl-data.csv'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/stock-market-dag.py", line 35, in get_stock_data
    df.to_csv('/usr/local/spark/resources/data/tmp/{}/{}-data.csv'.format(start_date.strftime("%Y-%m-%d"), stock.lower()), header=False)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 3402, in to_csv
    storage_options=storage_options,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/spark/resources/data/tmp/2021-03-15/aapl-data.csv'
[2021-03-16 00:56:29,236] {{taskinstance.py:1194}} INFO - Marking task as UP_FOR_RETRY. dag_id=marketvol, task_id=get_apple_data, execution_date=20210316T005617, start_date=20210316T005628, end_date=20210316T005629
[2021-03-16 00:56:33,537] {{local_task_job.py:102}} INFO - Task exited with return code 1
